features_dict = {
    "stock_status": "وضعیت موجودی یا وضعیت نو بودن",
    "originality": "اصالت",
    "piece_count": "تعداد قطعات، تعداد تکه‌ها",
    "material": "جنس",
    "type": "نوع",
    "capacity": "ظرفیت",
    "meterage": "متراژ",
    "item_count": "تعداد اقلام",
    "number_people": "تعداد نفرات",
    "size2": "اندازه ۲ , قطر",
    "power": "توان",
    "number_combs": "تعداد شانه",
    "carpet_density": "تراکم فرش",
    "background_color": "رنگ پس‌زمینه",
    "number_of_pieces": "تعداد قطعات",
    "width": "عرض",
    "has_remote": "دارای ریموت",
    "volume": "حجم",
    "how_install": "روش نصب",
    "lamp_number": "تعداد لامپ",
    "model": "مدل",
    "color": "رنگ",
    "material_kettle": "جنس کتری",
    "teapot_capacity": "ظرفیت قوری",
    "body_material": "جنس بدنه",
    "customer_cleaned_name": "نام تمیز مشتری",
    "analyzed_name": "نام تحلیل‌شده",
    "device_capacity": "ظرفیت دستگاه",
    "usage": "کاربرد",
    "energy_grade": "رده انرژی، مصرف انرژی",
    "dimensions": "ابعاد",
    "weight": "وزن",
    "blade_count": "تعداد تیغه",
    "burner_count": "تعداد شعله",
    "number_floors": "تعداد طبقات",
    "speeds_number": "تعداد سرعت",
    "heating_capacity": "ظرفیت گرمایشی",
    "steam_pressure": "فشار بخار",
    "scent": "رایحه",
    "filter_type": "نوع فیلتر",
    "suction_power": "قدرت مکش",
    "modes": "حالت‌ها",
    "climate": "اقلیم",
    "refrigerant": "مبرد",
    "special_cases": "موارد ویژه",
    "cooling_capacity": "ظرفیت سرمایشی",
    "ozone": "ازن",
    "steam_type": "نوع بخار",
    "number_drawers": "تعداد کشو",
    "tech_sewing": "فناوری خیاطی",
    "speed_sewing": "سرعت دوخت",
    "power_supply": "منبع تغذیه",
    "home_bar": "مینی‌بار",
    "ice_dispenser": "یخ‌ساز",
    "turbo": "توربو",
    "program_count": "تعداد برنامه",
    "kettle_capacity": "ظرفیت کتری",
    "voltage": "ولتاژ",
    "battery_time": "زمان باتری",
    "auto_stop": "توقف خودکار",
    "screen_size": "اندازه صفحه",
    "display_type": "نوع نمایشگر",
    "screen_quality": "کیفیت صفحه",
    "pitcher_material": "جنس پارچ",
    "number_pages": "تعداد صفحات",
    "number_houses": "تعداد خانه",
    "engine_power": "قدرت موتور",
    "direction_of_ventilation": "جهت تهویه",
    "fan": "پنکه",
    "needs_chimney": "نیاز به دودکش",
    "bowl_material": "جنس کاسه",
    "temperature": "دما",
    "people_capacity": "ظرفیت نفر",
    "radiator_length": "طول رادیاتور",
    "engine_type": "نوع موتور",
    "product_shape": "شکل محصول",
    "pulse": "پالس",
    "number_grids": "تعداد شبکه",
    "output_capacity": "ظرفیت خروجی",
    "reverse_rotation": "چرخش معکوس",
    "control_panel": "پنل کنترل",
    "number_slices": "تعداد برش",
    "basket_count": "تعداد سبد",
    "water_consumption": "مصرف آب",
    "rotating_tray": "سینی چرخان",
    "brand": "برند",
    "supplier": "تأمین‌کننده",
    "gemstone": "سنگ قیمتی",
    "clean": "تمیز",
    "display": "نمایشگر",
    "max_height": "حداکثر ارتفاع",
    "sensor_type": "نوع سنسور"
}
